### ISSUE TITLE
[Bug]: Wifi USB flash drive doesn't find by the os

### ISSUE THREAD

**Issue by Supernatnat11** [MassOS-Linux/MassOS#41]
### Checklist

- [X] I have searched for [other issues](https://www.github.com/MassOS-Linux/MassOS/issues), and can confirm my issue has not already been reported.
- [X] If this is an issue with a specific program, I have checked the upstream project's issue tracker and determined that it is an issue with MassOS itself.

### MassOS version

2022.06

### Kernel version

Linux 5.18.1-massos

### Subject

- [x] Issue at runtime of MassOS.
- [X] Issue with the MassOS Live CD.
- [ ] Issue with installing MassOS.
- [ ] Issue with the MassOS documentation.
- [ ] Issue compiling MassOS from source.

### Expected Behavior

I have plug my Wi-Fi flash drive on my computer and the Network tabs add all the detected Wi-Fi around the computer. 

### Actual Behavior

The network tabs just want to connect with Ethernet and I don't have Ethernet connection on my computer but I have a Wi-Fi flash drive. He doesn't show me other methods to connect when the Wi-Fi flash drive is plug. 

### Additional Information

The Wi-Fi flash drive is a Essentielb Wifi AC 1200 USB 3.0 Wi-Fi Key.

**Comment by DanielMYT** [comment]
Open a terminal (Control+Alt+T or find the terminal application) and run the command `lsusb`. With that you should be able to find out whether the Wi-Fi dongle is detected by the system, and if so, the model of the onboard network controller (please send that here if possible).

It is possible that the dongle requires a third party driver which is not included in the Linux Kernel or linux-firmware. It's uncommon, but I've heard of this being the case with some USB network adapters (particularly obscure ones with Realtek controllers, which this one might be).

Since I do not have access to this particular piece of hardware, I cannot test it, however I found [this thread](https://forum.ubuntu-fr.org/viewtopic.php?id=2060172) on a French Ubuntu forum website mentioning the particular device, and although I don't speak French, the thread refers to [another thread](https://forum.ubuntu-fr.org/viewtopic.php?id=2050755) which contains some commands to what appears to be the installation of a third party driver, which may be the one necessary for your dongle.

Although the posts I referenced are on a forum site for Ubuntu, the commands look like generic GNU/Linux ones which should also be supported on MassOS, as MassOS includes the packages which should be needed. You will obviously need to verify this yourself and do your own research, but hopefully this points you in the right direction.

Also, as a side note, I recommend [upgrading](https://github.com/MassOS-Linux/MassOS/wiki/Upgrading-MassOS) to the [latest version of MassOS](https://github.com/MassOS-Linux/MassOS/releases) when you can. Although the upgrade utility requires an internet connection, the Live CD refresh method doesn't need an internet connection, assuming you already have the ISO downloaded.

**Comment by Supernatnat11** [comment]
I'm French and I read the forum and he speaks to download a file from github, but to install the driver for wifi, I need wifi? I don't really understand.

**Comment by DanielMYT** [comment]
Do you have another machine or OS you can use to download the necessary files, and then copy/transfer them to your MassOS system?

**Comment by Supernatnat11** [comment]
It's good, I did it. Thanks you very much

**Comment by DanielMYT** [comment]
Glad you got it working.
